### ISSUE TITLE
ガイドの「簡易に」というフレーズは不要

### ISSUE THREAD

**Issue by kyohei-nakamura** [TUBAME/tubame.github.io#18]
ラベルの各ガイドの「1.1.本ドキュメントの紹介」内で、「本マニュアルは、○○ツールの利用手順について簡易に説明したマニュアルです。」とありますが、本ガイド以外に詳細解説しているドキュメントはないため、ここでは「簡易に」というフレーズは不要と思いますがいかがでしょうか。

**Comment by TUBAME** [comment]
修正されていることを確認。
