### ISSUE TITLE
GUIの操作系は、guimenuタグを利用して、見易くする。

### ISSUE THREAD

**Issue by azkaoru** [TUBAME/tubame.github.io#24]
GUIの操作系は、guimenuとかを利用したほうが良い。

---

<para>
　　　　          <menuchoice>
                        <guimenuitem>tubame</guimenuitem>
                        <guimenuitem>ナレッジベース検索</guimenuitem>
                    </menuchoice>
## </para>

該当箇所は、
2.1.マイグレーションナレッジの準備
Window -> Open Perspective -> Other -> ナレッジ管理ツール

2.2.アイテムの作成・編集
XMLファイル右クリック -> Open With -> ナレッジエディタ

とか。

**Comment by TUBAME** [comment]
Closed #24
