### ISSUE TITLE
ナレッジベース検索のゴールはレポート生成（機能）で良いか

### ISSUE THREAD

**Issue by kyohei-nakamura** [TUBAME/tubame.github.io#27]
質問になってしまいますが、「2.1.2.検索結果編集機能」の項番7「報告書の出力」とありますが、今回レポート機能をテックプレビューにすることもあり、正常ルートとしてレポート生成機能を使用することが良いガイドなのかが検討する必要があると思います。
メインルートは「CSS出力してそれをユーザが好きに使用する」なのか「レポート生成機能を使用する」なのかどちらになるでしょうか。

**Comment by azkaoru** [comment]
メインルートは、FW及びJBossEAPの移植検討であれば、レポート生成機能を使用するほうが良いと思っています。Tomcatの移植検討では、レポート利用したことがないので、正直わからないです。
ユーザガイド的には、必要に応じて使い分けをしてもうら必要がありそうなので、それぞれの方法を記載したほうが良いね。

**Comment by kyohei-nakamura** [comment]
対応ありがとうございます。
本issue はクローズします。
